### ISSUE TITLE
Proposal: Improve type

### ISSUE THREAD

**Issue by emulienfou** [HelisLT/settings-manager-bundle#54]
This issue would be more a suggestion about the `type` option.
Currently, available values are: `string`, `bool`, `int`, `float`, `yaml` and `choice`.
With this king of design, there is a limited amount of values available.

Let says you want to add a settings for an email field, a textarea field, or a choice field to be rendered has radio or checkbox buttons, currently this options are not available.

This issue would suggest to use, like [EasyAdminBundle](https://github.com/EasyCorp/EasyAdminBundle) the default form types provided by Symfony itself, listed right here: https://symfony.com/doc/4.1/reference/forms/types.html

In that case, a user would be able to wright something like:
```yaml
settings:
  - name: foo
    type: string
  - name: bar
    type: Symfony\Component\Form\Extension\Core\Type\TextType
  - name: foo2
    type: Symfony\Component\Form\Extension\Core\Type\TextareaType
```

So, it should be great to add a new configuration option `type_options` to be able to customize every form types rendered. Here is an example for the Choice type to render a select, radio or checkbox:
```yaml
settings:
  - name: select_multiple
    type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
    type_options:  { multiple: true }
  - name: radio
    type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
    type_options:  { expanded: true, multiple: false }
  - name: checkbox
    type: Symfony\Component\Form\Extension\Core\Type\ChoiceType
    type_options:  { expanded: true, multiple: true }
```

However, to still support the current available options: `string`, `bool`, `int`, `float`, `yaml` and `choice` it will require to add a mapping from name to class, like done in the **EasyAdminBundle**

https://github.com/EasyCorp/EasyAdminBundle/blob/420fa1863dc51be49ec308588d62a1f01ed9536d/src/Form/Util/FormTypeHelper.php#L56

@martiis what do you think about this proposal?
